name: retrogsf-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - rdkit
  - aizynthfinder
  - streamlit
  - pandas
  - numpy
  - pillow
  - requests
  - python-dotenv
  - pip
  - pip:
      - protobuf>=4.22.3

